### ISSUE TITLE
LUA Error since update

### ISSUE THREAD

**Issue by livvy7678** [ronnievdc/gear-overview#1]
Screenshot attached
![Elder Scrolls  Online Screenshot 2022 05 10 - 09 58 58 60](https://user-images.githubusercontent.com/105248963/167505654-733b927a-c4da-48c3-b65a-1e6d48ac304d.png)

**Comment by livvy7678** [comment]
Also unable to open and use addon

**Comment by ronnievdc** [comment]
Thanks for the notice, i'll look into it.

**Comment by ronnievdc** [comment]
Fixed in e46fbcbc14569436d8093851360a58aaa6090b77

@livvy7678 The fix should be available soon in Minion
