### ISSUE TITLE
Error when showing gear

### ISSUE THREAD

**Issue by mughetto** [ronnievdc/gear-overview#2]
for the last few days I get the following error after clicking "Show My Gear":

> bad argument #1 to 'pairs' (table/struct expected, got nil)
> stack traceback:
> [C]: in function 'pairs'
> user:/AddOns/GearOverview/GearOverviewUtils.lua:118: in function 'lib.fetchItems'
> user:/AddOns/GearOverview/GearOverviewUI.lua:109: in function 'lib.refreshGearList'
> 	<Locals> myList = [table:1]{} </Locals>
> user:/AddOns/GearOverview/GearOverviewUI.lua:155: in function 'lib.switchTab'
> 	<Locals> tab = "GEAR" </Locals>
> user:/AddOns/GearOverview/GearOverviewUI.lua:303: in function '(anonymous)'

This happens with or without a preset selected. I'm using version 0.9.0 from Minion.

Cheers

**Comment by ronnievdc** [comment]
Thank you for posting this issue.

It looks like Inventory Insight had an major update, where the access to the database has changed. I've updated my code to work with both the old and the new version.

Version 0.9.1 which fixes this issue should be available soon in Minion.
Can you verify this also fixed your issue?

For code details check: 1cc1e41741a5053a1d870c76bf1fc4a0fdee3b79

**Comment by mughetto** [comment]
Hey @ronnievdc sorry for the delay,w as away from the computer :)

0.9.1 fixes it perfectly, thanks a lot!
